services:
  - type: web
    name: your-flask-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: UPLOAD_FOLDER
        value: /var/uploads
      - key: ALLOWED_EXTENSIONS
        value: .jpg,.jpeg,.png